### PR TITLE
Onehrxn

### PR DESCRIPTION
**Pull request by onehr**
Try to add rustfmt.toml and run `cargo fmt` before commit.
If you like to work together and make the code format specified, consider using `cargo fmt`.

### CODE REVIEW

**Comment by ffwff** [comment]
Thanks! Could you pull from latest and reformat it?

**Comment by onehr** [comment]
Sorry, got little busy those days, I will do it tonight or tomorrow night.

**Comment by ffwff** [comment]
I think I'll manually add the `rustfmt.toml` file and reformat it then.

**Comment by onehr** [comment]
Sure, that would be fine.

**Pull request closed without merging**
